### ISSUE TITLE
slider

### ISSUE THREAD

**Issue by Arshavir-Gasparyan** [Arshavir-Gasparyan/bookstore#2]
add this text.
Yes, this is the interior of the Book Store in #Armenia. Mind blowing, isn't it? 🤯
The building was built in 1940 and the book store was initially a tobacco shop, that's why it has an Eastern style interior. Later it became a musical store and from the end of 1960 they started to sell books, too. 📙 
From 1990 the store was bought by Andranik Shoghunts and officially became a book store.
For over 25 years the store is managed by Karen Gasparyan, whom you can see in photos

**Comment by Vahe787** [comment]
Text is added

**Comment by Arshavir-Gasparyan** [comment]
good job @Vahe787
